### ISSUE TITLE
Regarding Licence

### ISSUE THREAD

**Issue by nmakes** [IDEA-Research/UniPose#13]
Hello! Thanks for open-sourcing the great work! Could you please confirm the Licence associated with this repository and the models?

**Comment by ailingzengzzz** [comment]
Hi @nmakes,

Thanks for your kind reminder. I have updated our license [here](https://github.com/IDEA-Research/UniPose/blob/master/LICENSE.txt).

**Comment by nmakes** [comment]
Thanks for the update!
