### ISSUE TITLE
only input images

### ISSUE THREAD

**Issue by huihui0613** [IDEA-Research/UniPose#2]
In the inference stage, only input images, can I get the keypoints of the object?

**Comment by yangjie-cv** [comment]
Thank you for your interest. We have included predefined keypoints, so there's no need to provide a keypoint text prompt. You can proceed with the image inference using the following command:

python inference_on_a_image.py -c config/UniPose_SwinT.py -p weights/unipose_swint.pth -i image_you_want_to_test.jpg -o "dir you want to save the output" -t "person"
