### ISSUE TITLE
Method name is copied from CVPR published Pose Estimation paper

### ISSUE THREAD

**Issue by bmartacho** [IDEA-Research/UniPose#7]
Dear authors,

The name of your method "UniPose" refers to a Human Pose Estimation method that already exists and was published at CVPR 2020 (https://openaccess.thecvf.com/content_CVPR_2020/html/Artacho_UniPose_Unified_Human_Pose_Estimation_in_Single_Images_and_Videos_CVPR_2020_paper.html). Despite using the exact same name for the same application (which is not allowed), there was also no proper citation of previous works in the area.

Please rename your method, respecting copyright and plagiarism rules for scientific publications.

**Comment by yangjie-cv** [comment]
hi, we will update the new Axriv version within a month and rename the model to "X-Pose".
